services:
  db:
    image: postgres:16-alpine
    container_name: portafolio-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - datos_db:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: portafolio-backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: portafolio-frontend
    restart: unless-stopped
    env_file: ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  datos_db:
